/********************************************************************
* librad-spec-tools-rdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error librad-spec-tools-rdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_inheritancelibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_typetablelibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_memvarlibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_globallibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_memfunclibradmIspecmItoolsmIrdict();
extern void G__cpp_setup_funclibradmIspecmItoolsmIrdict();
extern void G__set_cpp_environmentlibradmIspecmItoolsmIrdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Binning.h"
#include "HistAnalysis.h"
#include "SDCalibrator.h"
#include "SDFitData.h"
#include "SDMultiLineFitter.h"
#include "SDPeak.h"
#include "SDPeakTSF.h"
#include "SDPreCal.h"
#include "rsptutils.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_ROOT;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TList;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TAxis;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rspt;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLBinning;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TF1;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TH1;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_ROOTcLcLMath;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_ROOTcLcLMathcLcLParamFunctor;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TSpectrum;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TSpectrumFit;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLHistAnalysis;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TCanvas;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TGraph;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_TGraphErrors;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDFitData;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDCalibrator;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDMultiLineFitter;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlErsptcLcLSDFitDatamUcOallocatorlErsptcLcLSDFitDatamUgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_reverse_iteratorlEvectorlErsptcLcLSDFitDatamUcOallocatorlErsptcLcLSDFitDatamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_pairlEdoublecOintgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDPeak;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLMultiPeakShape;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDPeakTSF;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLMultiPeakShapeTSF;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDPreCal;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLDescriptiveStatisticslEfloatgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_pairlErsptcLcLDescriptiveStatisticslEdoublegRcOrsptcLcLDescriptiveStatisticslEdoublegRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_pairlEdoublecOdoublegR;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_rsptcLcLSDPreCalcLcLnext_line_info;
extern G__linked_taginfo G__libradmIspecmItoolsmIrdictLN_pairlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcOrsptcLcLDescriptiveStatisticslEfloatgRsPgR;

/* STUB derived class for protected member access */
